# /etc/jpacker/jpacker.conf

# ------------------------------------------------------------------
# jpacker configuration file
# ------------------------------------------------------------------

# [PKGBUILD Review]
# Set to true to skip the interactive PKGBUILD review prompt.
# Default: false
# NOEDIT=true

# [Editor]
# Specify the preferred text editor for reviewing PKGBUILDs and editing configs.
# If not set, the environment variable 'EDITOR' is used.
# Fallback: nano
# EDITOR=vim

# [Logging]
# Specify the log file path.
# Default: ~/.cache/jpacker/jpacker.log
# You can use '~' to refer to the user's home directory.
# LOGFILE=~/logs/jpacker.log
# LOGFILE=/var/log/jpacker.log
