#!/bin/sh
set -eu

printf 'pacman-conf %s\n' "$*" >> "$JPACKER_TEST_COMMAND_LOG"

if [ "$#" -ne 3 ] ||
   [ "${1:-}" != "--verbose" ] ||
   [ "${2:-}" != "RootDir" ] ||
   [ "${3:-}" != "DBPath" ]; then
    exit 2
fi

exit_code=${JPACKER_TEST_PACKAGE_METADATA_PACMAN_CONF_EXIT_CODE:-0}
if [ "$exit_code" -ne 0 ]; then
    exit "$exit_code"
fi

printf 'RootDir = /\nDBPath = /var/lib/pacman\n'
