#!/bin/sh
set -eu

printf 'pacman-conf %s\n' "$*" >> "$MOGUET_TEST_COMMAND_LOG"

if [ "$#" -ne 3 ] ||
   [ "${1:-}" != "--verbose" ] ||
   [ "${2:-}" != "RootDir" ] ||
   [ "${3:-}" != "DBPath" ]; then
    exit 2
fi

exit_code=${MOGUET_TEST_PACKAGE_METADATA_PACMAN_CONF_EXIT_CODE:-0}
failure_at=${MOGUET_TEST_PACKAGE_METADATA_PACMAN_CONF_FAILURE_AT:-}
case $failure_at in
    '')
        should_fail=1
        ;;
    *[!0-9]*)
        exit 2
        ;;
    *)
        call_count=$(grep -Fxc -- 'pacman-conf --verbose RootDir DBPath' "$MOGUET_TEST_COMMAND_LOG")
        if [ "$call_count" -eq "$failure_at" ]; then
            should_fail=1
        else
            should_fail=0
        fi
        ;;
esac
if [ "$should_fail" -eq 1 ] && [ "$exit_code" -ne 0 ]; then
    exit "$exit_code"
fi

printf 'RootDir = /\nDBPath = /var/lib/pacman\n'
