# /etc/jpacker/jpacker.conf

# Editor command
# EDITOR=vim

# Skip PKGBUILD review (default: false)
# NOEDIT=true

# Skip git diff check on update (default: false)
# NODIFF=true

# Log file
# LOGFILE=~/logs/jpacker.log
