# Generated by scripts/generate_completions.py; do not edit.
# Description locale: en
# Canonical closed grammar (projected from src/cli_authority.hpp):
#   build <pkg> [V=K...]
#   build --local <directory> [V=K...]
#   upgrade
#   upgrade-aur
#   upgrade-all
#   clean
#   deps [--recursive] <pkg>...
#   plan <pkg>...
#   fetch <pkg>...
#   add-src <item>...
#   edit-src <pkg>...
#   list-src
#   del-src <pkg>...
#   revert <pkg>...
#   -G <pkg>
#   -Gp <pkg>
#   -S --select [--needed] <query>

_moguet_option_id() {
    case "$1" in
        -h|--help) printf '%s' 13 ;;
        -V|--version) printf '%s' 14 ;;
        --edit) printf '%s' 0 ;;
        --noedit) printf '%s' 1 ;;
        --diff) printf '%s' 2 ;;
        --nodiff) printf '%s' 3 ;;
        --noconfirm) printf '%s' 4 ;;
        --dry-run) printf '%s' 5 ;;
        --build-mode|--build-mode=*) printf '%s' 6 ;;
        --rebuild) printf '%s' 7 ;;
        --cleanbuild) printf '%s' 8 ;;
        --rmdeps) printf '%s' 9 ;;
        --select) printf '%s' 10 ;;
        --aur) printf '%s' 11 ;;
        --repo) printf '%s' 12 ;;
        --local) printf '%s' 15 ;;
        --recursive) printf '%s' 16 ;;
        --needed) printf '%s' 17 ;;
        *) return 1 ;;
    esac
}

_moguet_has_option_id() {
    local expected="$1" word actual
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        actual="$(_moguet_option_id "$word" || true)"
        [[ $actual == "$expected" ]] && return 0
    done
    return 1
}

_moguet_find_operation() {
    local word
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        case "$word" in
        -h|--help|-V|--version|build|upgrade|upgrade-aur|upgrade-all|clean|deps|plan|fetch|add-src|edit-src|list-src|del-src|revert|-G|-Gp|-S|-Syu|-Ss|-Si|-Qua) printf '%s' "$word"; return 0 ;;
        esac
        _moguet_option_id "$word" >/dev/null && continue
        if [[ $word == -* ]]; then
            printf '%s' __delegated__
            return 0
        fi
    done
    return 1
}

_moguet_has_operand() {
    local expected_operation="$1" word actual seen_operation=false
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $seen_operation == false ]]; then
            if [[ $word == "$expected_operation" ]]; then
                seen_operation=true
            fi
            continue
        fi
        actual="$(_moguet_option_id "$word" || true)"
        [[ -z $actual ]] && return 0
    done
    return 1
}

_moguet_conflicts_with_present_option() {
    case "$1" in
        0) _moguet_has_option_id 1 ;;
        1) _moguet_has_option_id 0 ;;
        2) _moguet_has_option_id 3 ;;
        3) _moguet_has_option_id 2 ;;
        6) _moguet_has_option_id 7 || _moguet_has_option_id 8 ;;
        7) _moguet_has_option_id 6 || _moguet_has_option_id 8 ;;
        8) _moguet_has_option_id 6 || _moguet_has_option_id 7 ;;
        9) _moguet_has_option_id 10 ;;
        10) _moguet_has_option_id 9 ;;
        11) _moguet_has_option_id 12 ;;
        12) _moguet_has_option_id 11 ;;
        *) return 1 ;;
    esac
}

_moguet() {
    local cur operation candidate option_id
    local -a candidates filtered
    cur="${COMP_WORDS[COMP_CWORD]}"
    operation="$(_moguet_find_operation || true)"

    if [[ -z $operation ]]; then
        candidates=(build upgrade upgrade-aur upgrade-all clean deps plan fetch add-src edit-src list-src del-src revert -G -Gp -S -Syu -Ss -Si -Qua -h --help -V --version --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --rmdeps --select --aur --repo)
    else
        case "$operation" in
        build)
            if _moguet_has_option_id 15; then
                candidates=(--edit --noedit --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --local)
            elif _moguet_has_operand build; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --local)
            fi
            ;;
        upgrade)
            if _moguet_has_operand upgrade; then
                candidates=()
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            fi
            ;;
        upgrade-aur)
            if _moguet_has_operand upgrade-aur; then
                candidates=()
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            fi
            ;;
        upgrade-all)
            if _moguet_has_operand upgrade-all; then
                candidates=()
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            fi
            ;;
        clean)
            if _moguet_has_operand clean; then
                candidates=()
            else
                candidates=(--noconfirm)
            fi
            ;;
        deps) candidates=(--noconfirm --recursive) ;;
        plan) candidates=(--noconfirm) ;;
        fetch) candidates=(--noconfirm --dry-run) ;;
        add-src) candidates=() ;;
        edit-src) candidates=() ;;
        list-src)
            if _moguet_has_operand list-src; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        del-src) candidates=() ;;
        revert) candidates=(--noconfirm) ;;
        -G) candidates=() ;;
        -Gp) candidates=() ;;
        -S)
            if _moguet_has_option_id 10; then
                candidates=(--select --needed --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --aur --repo)
            else
                candidates=(--needed --noconfirm --select)
            fi
            ;;
        -Syu) candidates=(--needed --noconfirm) ;;
        -Ss) candidates=(--needed --noconfirm) ;;
        -Si) candidates=(--needed --noconfirm) ;;
        -Qua) candidates=(--needed --noconfirm) ;;
        -h) candidates=() ;;
        --help) candidates=() ;;
        -V) candidates=() ;;
        --version) candidates=() ;;
        __delegated__) candidates=(--needed --noconfirm) ;;
        *) candidates=() ;;
        esac
    fi

    filtered=()
    for candidate in "${candidates[@]}"; do
        option_id="$(_moguet_option_id "$candidate" || true)"
        if [[ -n $option_id ]]; then
            case "$option_id" in
            13|14|15)
                _moguet_has_option_id "$option_id" && continue
                ;;
            esac
            _moguet_conflicts_with_present_option "$option_id" && continue
        fi
        filtered+=("$candidate")
    done

    COMPREPLY=()
    COMPREPLY=( $(compgen -W "${filtered[*]}" -- "$cur" || true) )
}

complete -F _moguet moguet
