# Generated by scripts/generate_completions.py; do not edit.
# Description locale: en

_moguet() {
    local cur
    local -a operations=(
        build
        upgrade
        upgrade-aur
        upgrade-all
        clean
        deps
        plan
        fetch
        add-src
        del-src
        revert
        edit-src
        list-src
        -G
        -Gp
        -S
        -Syu
        -Ss
        -Si
        -Qua
    )
    local -a options=(
        -h
        --help
        -V
        --version
        --edit
        --noedit
        --diff
        --nodiff
        --noconfirm
        --dry-run
        --build-mode=
        --rebuild
        --cleanbuild
        --rmdeps
        --select
        --aur
        --repo
        --needed
        --local
        --recursive
    )

    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=( $(compgen -W "${operations[*]} ${options[*]}" -- "$cur" || true) )
}

complete -F _moguet moguet
