#!/bin/sh
set -eu

printf 'moguet-test-editor %s\n' "$*" >> "$MOGUET_TEST_COMMAND_LOG"

target=
for editor_argument in "$@"; do
    target=$editor_argument
done

if [ -z "$target" ]; then
    exit 1
fi

snapshot_file=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_SNAPSHOT_FILE:-}
if [ -n "$snapshot_file" ]; then
    /usr/bin/cp -- "$target" "$snapshot_file"
fi

fail_substring=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_FAIL_SUBSTRING:-}
case $target in
    *"$fail_substring"*)
        if [ -n "$fail_substring" ]; then
            exit 1
        fi
        ;;
esac

if [ "${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_APPEND_LINE+x}" = "x" ]; then
    printf '%s\n' "$MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_APPEND_LINE" >> "$target"
fi

replacement_kind=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_REPLACEMENT_KIND:-}
replacement_substring=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_REPLACEMENT_SUBSTRING:-}
replace_target=0
if [ -n "$replacement_kind" ]; then
    if [ -z "$replacement_substring" ]; then
        replace_target=1
    else
        case $target in
            *"$replacement_substring"*) replace_target=1 ;;
        esac
    fi
fi

if [ "$replace_target" -eq 1 ]; then
    case $replacement_kind in
        symlink)
            replacement_target=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_REPLACEMENT_TARGET:-}
            if [ -z "$replacement_target" ]; then
                exit 2
            fi
            /usr/bin/rm -f -- "$target"
            /usr/bin/ln -s -- "$replacement_target" "$target"
            ;;
        directory)
            /usr/bin/rm -f -- "$target"
            /usr/bin/mkdir -- "$target"
            ;;
        fifo)
            /usr/bin/rm -f -- "$target"
            /usr/bin/mkfifo -- "$target"
            ;;
        missing)
            /usr/bin/rm -f -- "$target"
            ;;
        regular)
            replacement_source=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_REPLACEMENT_SOURCE:-}
            if [ -z "$replacement_source" ] || [ ! -f "$replacement_source" ]; then
                exit 2
            fi
            /usr/bin/rm -f -- "$target"
            /usr/bin/cp -- "$replacement_source" "$target"
            ;;
        *)
            exit 2
            ;;
    esac
fi

concurrent_destination=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_CONCURRENT_DESTINATION:-}
if [ -n "$concurrent_destination" ]; then
    concurrent_contents=${MOGUET_TEST_SOURCE_MAINTENANCE_EDITOR_CONCURRENT_CONTENTS:-}
    /usr/bin/rm -f -- "$concurrent_destination"
    printf '%s\n' "$concurrent_contents" > "$concurrent_destination"
    /usr/bin/chmod 600 -- "$concurrent_destination"
fi

exit 0
